import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='bg-invert min-h-screen flex flex-col max-w-7xl mx-auto'>
        <div className='min-h-full lg:py-20 py-10  lg:px-10 px-4'>
          {children}
        </div>
      </body>
    </html>
  );
}
